---
title: "Gov 50 Final Project"
author: Sarah Park
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to how the environmental index in different countries relates to the mortality rate in these different countries. I think this is interesting because environmental harm such as pollution can impact mortality rate as it can cause health issues.

##Milestone 2
I will use British Election study data on https://www.britishelectionstudy.com/data/. My research question is: does party impact an individual's view on environmental protection? My hypothesis is that the more progressive a party is, the more likely they are to vote for environmental protection. My variables of interest are the types of parties in Britain (such as the Labour Party, Conservatives, Liberal Democrats, UKIP, Green Party, SNP, and Plaid Cymru) and their response to a survey on whether measures to protect the environment have not gone nearly far enough or have gone much too far. The variation is the different parties and their different numeric responses to the survey. An observed pattern in the data that would provide support for my hypothesis would be that specific parties that tend to support more progressive policies would be more passionate about the environment -- and thus, respond with a lower number on whether they think measures to protect the environment have gone far enough. My sample is comprised of data from the years 2014, 2015, and 2017 from the British Election study data pertaining to environmental protection. My outcome variable is the response to the question.
